#!/bin/bash

BLUEALSA=$(ps cax | grep -v grep | grep bluealsa)
if [ "$BLUEALSA" == "" ] ; then
  sudo bluealsa &
fi

PYUDEVMONDT=$(ps cax | grep -v grep | grep pyudevmondt)
if [ "$PYUDEVMONDT" == "" ] ; then
  sudo /usr/lib/dirtytooth/pyudevmondt &
fi

sudo hciconfig hci0 name "Dirtytooth Speaker"
sudo hciconfig hci0 class 0x240418
sudo hciconfig hci0 sspmode 1
sudo hciconfig hci0 piscan
/usr/lib/dirtytooth/dirtyagent &
