#!/bin/bash
# Postinstallation dirtytooth package

nobexurl="https://github.com/nccgroup/nOBEX.git"
nobexcommit="0583c72"

# Detect if PyBluez is installed
pybluez=$(pip list | grep PyBluez)
if [ "$pybluez" == "" ] ; then
    sudo pip install pybluez==0.22
fi

# Detect if nOBEX is installed
nobex=$(pip list | grep nOBEX)
if [ "$nobex" == "" ] ; then
    cd /tmp
    git clone $nobexurl
    cd nOBEX
    git reset --hard $nobexcommit
    python setup.py install
    cd /tmp
    rm -rf nOBEX
fi

# Detect if psutil is installed
psutil=$(pip list | grep psutil)
if [ "$psutil" == "" ] ; then
    sudo pip install psutil==5.2.2
fi

# Detect if watchdog is installed
watchdog=$(pip list | grep watchdog)
if [ "$watchdog" == "" ] ; then
    sudo pip install watchdog==0.8.3
fi

# Add audio hook
# audiohook=$(cat /etc/udev/rules.d/99-com.rules | grep /usr/lib/udev/bluetooth)
# if [ "$audiohook" == "" ] ; then
#     sudo sed -i '/SUBSYSTEM=="input".*/a KERNEL=="input\[0-9\]*", PROGRAM="/usr/lib/udev/bluetooth"' /etc/udev/rules.d/99-com.rules
# fi

MAC_ADAPTER=$(hcitool dev | grep -o "[[:xdigit:]:]\{11,17\}")

# Add info to asoundrc
asoundrc=/root/.asoundrc
echo "defaults.bluealsa.interface \"hci0\"" > $asoundrc
echo "defaults.bluealsa.device \"$MAC_ADAPTER\"" >> $asoundrc
echo "defaults.bluealsa.profile \"a2dp\"" >> $asoundrc
echo "defaults.bluealsa.delay 10000" >> $asoundrc

echo "Dirtytooth installation finished"
exit 0
